name: Sync GitHub to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ============================
      # GitLab.com
      # ============================

      - name: Push to GitLab.com
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: ${{ secrets.GITLAB_REPO }}
        run: |
          git remote add gitlab-com \
            https://oauth2:${GITLAB_TOKEN}@gitlab.com/${GITLAB_REPO}

          git push gitlab-com main:main --force

      # ============================
      # GitLab Pemkot Bekasi
      # ============================

      - name: Push to GitLab Bekasi
        env:
          BEKASI_GITLAB_TOKEN: ${{ secrets.BEKASI_GITLAB_TOKEN }}
          BEKASI_GITLAB_REPO: ${{ secrets.BEKASI_GITLAB_REPO }}
        run: |
          git remote add gitlab-bekasi \
            https://oauth2:${BEKASI_GITLAB_TOKEN}@repo.bekasikota.go.id/${BEKASI_GITLAB_REPO}

          git push gitlab-bekasi main:main --force
